/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Lab Informatika
 */
public class tampilan extends javax.swing.JFrame {

    /**
     * Creates new form tampilan
     */
    public tampilan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableDataHewan = new javax.swing.JTable();
        Txtid = new javax.swing.JTextField();
        Txtnama_pemilik = new javax.swing.JTextField();
        Txtnama_hewan = new javax.swing.JTextField();
        Txtjenis_hewan = new javax.swing.JTextField();
        Txtnomor_telepon = new javax.swing.JTextField();
        Txtdurasi_titip = new javax.swing.JTextField();
        Txttotal_biaya = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        insert2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableDataHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(TableDataHewan);

        Txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidActionPerformed(evt);
            }
        });

        Txtnama_pemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtnama_pemilikActionPerformed(evt);
            }
        });

        Txtnama_hewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtnama_hewanActionPerformed(evt);
            }
        });

        Txtjenis_hewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtjenis_hewanActionPerformed(evt);
            }
        });

        Txtnomor_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtnomor_teleponActionPerformed(evt);
            }
        });

        Txtdurasi_titip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtdurasi_titipActionPerformed(evt);
            }
        });

        Txttotal_biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txttotal_biayaActionPerformed(evt);
            }
        });

        update.setText("update");

        delete.setText("hapus");

        insert2.setText("Simpan");
        insert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txttotal_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtdurasi_titip, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtnomor_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtjenis_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtnama_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtnama_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(insert2)
                        .addGap(29, 29, 29)
                        .addComponent(update)
                        .addGap(28, 28, 28)
                        .addComponent(delete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(Txtnama_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txtnama_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txtjenis_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtnomor_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Txtdurasi_titip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txttotal_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete)
                            .addComponent(update)
                            .addComponent(insert2))
                        .addGap(12, 12, 12))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtidActionPerformed

    private void Txtnama_pemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtnama_pemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtnama_pemilikActionPerformed

    private void Txtnama_hewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtnama_hewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtnama_hewanActionPerformed

    private void Txtjenis_hewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtjenis_hewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtjenis_hewanActionPerformed

    private void Txtnomor_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtnomor_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtnomor_teleponActionPerformed

    private void Txtdurasi_titipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtdurasi_titipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtdurasi_titipActionPerformed

    private void Txttotal_biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txttotal_biayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txttotal_biayaActionPerformed

    private void insert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert2ActionPerformed
        // TODO add your handling code here:
        
                dc.insert();
                dc.isitabel();
    }//GEN-LAST:event_insert2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDataHewan;
    private javax.swing.JTextField Txtdurasi_titip;
    private javax.swing.JTextField Txtid;
    private javax.swing.JTextField Txtjenis_hewan;
    private javax.swing.JTextField Txtnama_hewan;
    private javax.swing.JTextField Txtnama_pemilik;
    private javax.swing.JTextField Txtnomor_telepon;
    private javax.swing.JTextField Txttotal_biaya;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    public JTable getTableDataHewan() {
        return TableDataHewan;
    }

    public void setTableDataHewan(JTable TableDataHewan) {
        this.TableDataHewan = TableDataHewan;
    }

    public JTextField getTxtdurasi_titip() {
        return Txtdurasi_titip;
    }

    public void setTxtdurasi_titip(JTextField Txtdurasi_titip) {
        this.Txtdurasi_titip = Txtdurasi_titip;
    }

    public JTextField getTxtid() {
        return Txtid;
    }

    public void setTxtid(JTextField Txtid) {
        this.Txtid = Txtid;
    }

    public JTextField getTxtjenis_hewan() {
        return Txtjenis_hewan;
    }

    public void setTxtjenis_hewan(JTextField Txtjenis_hewan) {
        this.Txtjenis_hewan = Txtjenis_hewan;
    }

    public JTextField getTxtnama_hewan() {
        return Txtnama_hewan;
    }

    public void setTxtnama_hewan(JTextField Txtnama_hewan) {
        this.Txtnama_hewan = Txtnama_hewan;
    }

    public JTextField getTxtnama_pemilik() {
        return Txtnama_pemilik;
    }

    public void setTxtnama_pemilik(JTextField Txtnama_pemilik) {
        this.Txtnama_pemilik = Txtnama_pemilik;
    }

    public JTextField getTxtnomor_telepon() {
        return Txtnomor_telepon;
    }

    public void setTxtnomor_telepon(JTextField Txtnomor_telepon) {
        this.Txtnomor_telepon = Txtnomor_telepon;
    }

    public JTextField getTxttotal_biaya() {
        return Txttotal_biaya;
    }

    public void setTxttotal_biaya(JTextField Txttotal_biaya) {
        this.Txttotal_biaya = Txttotal_biaya;
    }

    
    

}
